name: loop_visitor
description: A way to loop through entities calling a user-defined handler on every iteration and process returned result
version: 0.4.2
homepage: https://aiurovet.com/
repository: https://github.com/aiurovet/loop_visitor/

environment:
  sdk: '>=2.18.7 <4.0.0'

dev_dependencies:
  async: ^2.10.0
  file: ^7.0.0
  lints: ^3.0.0
  test: ^1.16.0
